---
- name: Configure HTCondor Cluster
  hosts: all
  gather_facts: yes
  become: yes
  vars:
    condor_cluster_password: "password"
    central_manager_ip: "192.168.56.101"
    condor_config_path: "/etc/condor/condor_config"
  tasks:
    - name: Install HTCondor
      apt:
        name: condor
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == "apt"

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_pkg_mgr == "apt"
    
    - name: Create HTCondor directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: condor
      loop:
        - /etc/condor
        - /etc/condor/passwords.d

    - name: Configure Central Manager
      template:
        src: templates/condor_config.central_submit2.j2
        dest: /etc/condor/condor_config
      when: "'central_manager' in group_names"
    
    - name: Configure Execute Node
      template:
        src: templates/condor_config.execute2.j2
        dest: /etc/condor/condor_config
      when: "'execute_nodes' in group_names"

    - name: Ensure /var/log/condor directory exists
      file:
        path: /var/log/condor
        state: directory
        mode: '0750'
        owner: root
        group: condor
      when: "'central_manager' in group_names"  

    - name: Create shared_port_ad file
      file:
        path: /var/log/condor/shared_port_ad
        state: touch
        mode: '0640'
        owner: root
        group: condor
      when: "'central_manager' in group_names"  
    
    - name: Set CONDOR_CONFIG environment variable
      lineinfile:
        path: /etc/default/condor
        line: 'CONDOR_CONFIG={{ condor_config_path }}'
        create: yes
        state: present
    
    - name: Update condor.service to use custom config
      systemd:
        name: condor
        enabled: yes
        daemon_reload: yes
        state: restarted
      environment:
        CONDOR_CONFIG: /etc/condor/condor_config.local
    
    - name: Ensure passwords.d directory exists
      file:
        path: /etc/condor/passwords.d
        state: directory
        mode: '0750'
        owner: root
        group: condor

    - name: Set HTCondor cluster password
      shell: |
        echo "{{ condor_cluster_password }}" | condor_store_cred -c add -f /etc/condor/passwords.d/POOL
      args:
        creates: /etc/condor/passwords.d/POOL
    
    - name: Set permissions for POOL password file
      file:
        path: /etc/condor/passwords.d/POOL
        mode: '0600'
        owner: root
        group: condor

    - name: Restart HTCondor service
      service:
        name: condor
        state: restarted
